### PR TITLE
Fix socket.io 2.4.0 cors issue

### LINKED ISSUE #847: 'Access-Control-Allow-Origin' issue
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87

2，Reproduce step：
After compiling and packaging mcu, useA connects to mcu，The error is as follows:
index.js:204 server connection failed: Error: connect_error:https://10.239.44.113:8080
    at owt.js:9
(anonymous) @ index.js:204
Promise.then (async)
(anonymous) @ index.js:143
req.onreadystatechange @ rest-sample.js:12
XMLHttpRequest.send (async)
send @ rest-sample.js:19
createToken @ rest-sample.js:79
window.onload @ index.js:141
load (async)
runSocketIOSample @ index.js:134
(anonymous) @ (index):52
(index):1 Access to XMLHttpRequest at 'https://10.239.44.113:8080/socket.io/?EIO=3&transport=polling&t=NRGvA3V' from origin 'https://webrtc90.sh.intel.com:3004' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

3，Expected ：
useA connects to mcu normally

### PR DESCRIPTION
**Pull request by qwu16**
Fix #847

### CODE REVIEW

File: source/portal/socketIOServer.js [hunk 1]
```diff
@@ -355,6 +355,9 @@ var SocketIOServer = function(spec, portal, observer) {
   var startInsecure = function(port) {
     var server = require('http').createServer().listen(port);
     io = require('socket.io').listen(server, sioOptions);
+    io.origins((_, callback) => {
```
Comment (starwarfan) [inline source/portal/socketIOServer.js:358]: My suggestion is that follow the example on socket.io document:
`io.origins((origin, callback) => {
  if origin in allowedList { // May use regExp to match the origin
    return callback(null, true);
  }
  callback('origin not allowed', false);
});`
https://socket.io/docs/v2/server-api/#server-origins-fn

Comment (starwarfan) [reply source/portal/socketIOServer.js:358]: And add a configuration item in portal.toml

File: source/portal/index.js [hunk 2]
```diff
@@ -26,6 +26,7 @@ config.portal.ssl = config.portal.ssl || false;
 config.portal.force_tls_v12 = config.portal.force_tls_v12 || false;
 config.portal.reconnection_ticket_lifetime = config.portal.reconnection_ticket_lifetime || 600;
 config.portal.reconnection_timeout = Number.isInteger(config.portal.reconnection_timeout) ? config.portal.reconnection_timeout : 60;
+config.portal.cors = config.portal.cors || '*';
```
Comment (starwarfan) [inline source/portal/index.js:29]: 'cors' should be a list if multiple origins are allowed.  E.g. 'localhost:3001', 'localhost:3004' are both allowed.

File: source/portal/socketIOServer.js [hunk 3]
```diff
@@ -352,14 +352,22 @@ var SocketIOServer = function(spec, portal, observer) {
     sioOptions.pingTimeout = spec.pingTimeout * 1000;
   }
 
-  var startInsecure = function(port) {
+  var startInsecure = function(port, cors) {
     var server = require('http').createServer().listen(port);
     io = require('socket.io').listen(server, sioOptions);
+    io.origins((origin, callback) => {
+      if(cors !== '*'){
```
Comment (starwarfan) [inline source/portal/socketIOServer.js:359]: Use RegExp to match origin here instead of '!==' check. Strings like "127.0.0.*" should be supported.
You can refer to 'replaced_ip_address' configuration in webrtc_agent/agent.toml.

**Review by starwarfan — APPROVED** [review]
