### PR TITLE
Fix VAD not working issue

### LINKED ISSUE #780: 3300/console vad issue
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87
2，Reproduce step：
1, 3300/console  Open VAD Enabled and KeepActiveInputPrimary
2,Open the page, there are two streams in the mix, one of them will talk to the first position in the mix, which does not meet the above expectations
It is expected that is successful
3，Expected ：
mcu works normally, no crash, no error

### PR DESCRIPTION
**Pull request by qwu16**
Fix #780

### CODE REVIEW

File: source/agent/conference/conference.js [hunk 1]
```diff
@@ -1893,14 +1893,22 @@ var Conference = function (rpcClient, selfRpcId) {
     if ((room_id === roomId) && roomController) {
       if (typeof target.view === 'string') {
         const view = target.view;
+        const input = streams[activeInputStream] ?
+            activeInputStream : trackOwners[activeInputStream];
         room_config.views.forEach((viewSettings) => {
           if (viewSettings.label === view && viewSettings.video.keepActiveInputPrimary) {
-            roomController.setPrimary(activeInputStream, view);
+            if(streams[input].info.type === "webrtc") {
+                const videoTrackId = streams[input].media.tracks.filter(t => t.type === 'video').map(t => t.id).toString();
```
Comment (starwarfan) [inline source/agent/conference/conference.js:1901]: map(...).toString() converts a Array to string, if the Array contains more than 1 items(current simulcast streams have multiple video tracks), this has potential problems. You will pass a string like 'id1,id2' to setPrimary.
Use Array.find() or [0] to get exactly one element in the Array instead of calling Array.toString.

**Review by starwarfan — APPROVED** [review]
